export enum Permission {
    TASK_CREATE = `TASK_CREATE`,
    TASK_UPDATE = `TASK_UPDATE`,
    TASK_DELETE = `TASK_DELETE`,
    TASK_VIEW = `TASK_VIEW`,
    USER_CREATE = `USER_CREATE`,
    USER_DELETE = `USER_DELETE`,
    USER_VIEW = `USER_VIEW`,
    USER_UPDATE = `USER_UPDATE`,
    USER_UPDATE_ROLE = `USER_UPDATE_ROLE`
}